fix(auth): provide a default value for full name
PKUHPC/OpenSCOW pull request #1428
Opened 2024-09-13 03:32 UTC by link89

close https://github.com/PKUHPC/SCOW/issues/1426

2024-09-17 16:20 UTC, ddadaal requested changes

2024-09-17 16:20 UTC, ddadaal commented on apps/auth/src/auth/ssh/index.ts
> +        }
这一段可以改写为`const fullName = gecosField?.split(",")?.[0] || passwdItems[0]`，更简洁

2024-09-18 01:03 UTC, link89 commented on apps/auth/src/auth/ssh/index.ts
> +        }
谢谢指正，已修复

2024-09-20 11:59 UTC, ddadaal approved these changes

2024-09-20 11:59 UTC, merged